site_name: TaskNotes Documentation
site_url: https://callumalpass.github.io/tasknotes/
site_description: Comprehensive task and note management with calendar integration for Obsidian
site_author: Callum Alpass
repo_name: callumalpass/tasknotes
repo_url: https://github.com/callumalpass/tasknotes

# Configuration
theme:
  name: material # Use the Material theme 
  # You can add theme-specific features here later, like palettes, fonts, logos, etc.
  features:
   # - navigation.tabs
   - search.suggest
  font:
   text: Crimson Text
  palette:
  - media: "(prefers-color-scheme)"
    accent: purple
    primary: white
    toggle:
     icon: material/brightness-auto
     name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    accent: purple
    primary: white
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    accent: purple
    primary: black
    toggle:
      icon: material/toggle-switch-off-outline

nav:
  - Home: index.md
  - Core Concepts: core-concepts.md
  - Features:
    - Overview: features.md
    - Task Management: features/task-management.md
    - Inline Task Integration: features/inline-tasks.md
    - Time Management: features/time-management.md
    - Calendar Integration: features/calendar-integration.md
  - Views:
    - Overview: views.md
    - Task List View: views/task-list.md
    - Notes View: views/notes-view.md
    - Agenda View: views/agenda-view.md
    - Kanban View: views/kanban-view.md
    - Pomodoro View: views/pomodoro-view.md
  - Settings:
    - Overview: settings.md
    - Task Defaults: settings/task-defaults.md
    - Inline Task Settings: settings/inline-task-settings.md
    - Calendar Settings: settings/calendar-settings.md
    - Advanced Settings: settings/advanced-settings.md
  - Release Notes: releases.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - attr_list

extra_css:
  - stylesheets/extra.css