name: Release Obsidian Plugin

on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: chronosync

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Plugin
        run: npm run build  # This includes CSS building via npm run build-css

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            main.js
            manifest.json
            styles.css
          draft: true